import * as fs from 'fs';
import * as fmt from '../../application/presentation/cli-format.js';
import { run } from '../git/git.js';
import { findMissionDir, findCheckpoints, resolveWorktree, inferSlug, missionBranchName } from '../filesystem/mission-utils.js';
import { resolveTaskFile, getTaskStatus, getTaskImplementer } from '../backlog/backlog.js';
import { getPrStatus } from './review-adapter.js';
import { readReviewState, reconcileInterruptedHandoff } from './review-state.js';
import type { MissionStore } from '../../application/domain-ports.js';
import { startAgent } from '../agents/agents.js';
import { resolveArtifactDir, reviewArtifactPath } from './review-artifacts.js';
import { startReviewLoop, recordStageStatsSafe } from './review-loop.js';
import type { ReviewWorkflowContext, ReviewWorkflowPort } from '../../application/ports/review-workflow.js';
import { flagValue, readTextFlag } from './review-cli-flags.js';
import { backfillReviewHandler, closeMissionPr, commentRound, consumeArtifacts, createEventHandler, formatStaticReviewSuccess, importLegacyHandler, performStaticReview, postStaticReviewComment, pushRound, readComments, reconcileInterruptedHandoffHandler, showReviewStatus, submitForReview, submitReviewRound, verifyReview } from './review-commands.js';

const DEFAULT_MAX_ATTEMPTS = 5;

export class ReviewWorkflowAdapter implements ReviewWorkflowPort {
  constructor(private readonly _defaults: {
    inferSlugFn?: typeof inferSlug; log?: (_msg: string) => void; error?: (_msg: string) => void; exit?: (_code: number) => never;
    verifyReviewFn?: typeof verifyReview; submitForReviewFn?: typeof submitForReview; consumeArtifactsFn?: typeof consumeArtifacts; pushRoundFn?: typeof pushRound; readCommentsFn?: typeof readComments; commentRoundFn?: typeof commentRound; submitReviewRoundFn?: typeof submitReviewRound; closeMissionPrFn?: typeof closeMissionPr; startReviewLoopFn?: typeof startReviewLoop; recordStageStatsSafeFn?: typeof recordStageStatsSafe; startAgentFn?: typeof startAgent; resolveTaskFileFn?: typeof resolveTaskFile; getTaskStatusFn?: typeof getTaskStatus; getTaskImplementerFn?: typeof getTaskImplementer; getPrStatusFn?: typeof getPrStatus; readReviewStateFn?: typeof readReviewState; performStaticReviewFn?: typeof performStaticReview; postStaticReviewCommentFn?: typeof postStaticReviewComment; resolveWorktreeFn?: typeof resolveWorktree; reconcileInterruptedHandoffFn?: typeof reconcileInterruptedHandoff;
    requireReviewAggregate?: boolean; missionStore?: MissionStore | null; run?: typeof run; missionPath?: string;
  } = {}) {}

  async preflight(args: string[], suppliedOptions: Record<string, unknown> = {}): Promise<ReviewWorkflowContext | null> {
    const options = { ...this._defaults, ...suppliedOptions } as typeof this._defaults; const slug = (options.inferSlugFn || inferSlug)(args.find(arg => !arg.startsWith('--')));
    if (!slug) { (options.error || fmt.log.plainError)('Usage: px review [<slug>] [--verify] [--submit] [--push] [--force] [--start|--continue [--implementer <a>] [--reviewer <a>] [--focus <f>] [--max-attempts <n>]] [--reconcile-review --branch <branch> --target <branch> --reviewer <agent> --implementer <agent> --revision <revision> --eligible-reviewer <agent>] [--no-gate] [--status] [--comments] [--comment "<msg>"|--comment-file <path>] [--submit-review <outcome> [--message "<summary>"|--message-file <path>] [--close] [--create-event --type <classification> [--input-file <path>] [--actor <name>] [--round <n>] [--phase <phase>] [--mission <path>]] [--import-legacy [--tmp-dir <dir>]] [--backfill-review [--dry-run]] [--consume-artifacts]'); (options.exit || process.exit)(1); return null; }
    return { slug, args, options };
  }
  async verify(context: ReviewWorkflowContext): Promise<void> { const o = context.options as typeof this._defaults; (o.verifyReviewFn || verifyReview)(context.slug, context.args.includes('--no-gate'), { ...o, missionPath: flagValue(context.args, '--mission') || undefined }); }
  async submit(context: ReviewWorkflowContext): Promise<void> { const o = context.options as typeof this._defaults; const dir = resolveArtifactDir((o.resolveWorktreeFn || resolveWorktree)(context.slug) || process.cwd()); if ([reviewArtifactPath(context.slug, 'review-findings.md', dir), reviewArtifactPath(context.slug, 'review-outcome.md', dir), reviewArtifactPath(context.slug, 'review-verdict.txt', dir)].some(fs.existsSync)) {(o.log || fmt.log.plain)(fmt.status('WARN', `Unprocessed review artifacts found at ${dir} for ${context.slug}. Consider using --consume-artifacts to persist them before handoff, or use --submit-review to post a verdict.`));} await (o.submitForReviewFn || submitForReview)(context.slug, context.args.includes('--no-gate'), o); }
  async push(context: ReviewWorkflowContext): Promise<void> { const o = context.options as typeof this._defaults; await (o.pushRoundFn || pushRound)(context.slug, { ...o, force: context.args.includes('--force') }); }
  async start(context: ReviewWorkflowContext): Promise<void> { await this.runLoop(context, false); }
  async continue(context: ReviewWorkflowContext): Promise<void> { await this.runLoop(context, true); }
  private async runLoop(context: ReviewWorkflowContext, isContinue: boolean): Promise<void> { const o = context.options as typeof this._defaults; const raw = flagValue(context.args, '--max-attempts'); const maxAttempts = raw === null ? DEFAULT_MAX_ATTEMPTS : parseInt(raw, 10); const error = o.error || fmt.log.plainError; const exit = o.exit || process.exit; if (!Number.isInteger(maxAttempts) || maxAttempts < 1) { error(fmt.status('FAIL', `--max-attempts requires a positive integer (got "${raw}").`)); exit(1); return; } const worktree = o.resolveWorktreeFn || resolveWorktree; if (o.requireReviewAggregate && !await Promise.resolve((o.readReviewStateFn || readReviewState)(context.slug, worktree(context.slug) || process.cwd(), o.missionStore))) { error(fmt.status('FAIL', `Mission ${context.slug} has no valid Review aggregate. Stop before reviewer launch and run px review ${context.slug} --reconcile-review --branch <branch> --target <branch> --reviewer <agent> --implementer <agent> --revision <revision> --eligible-reviewer <agent>.`)); exit(1); return; } const poll = flagValue(context.args, '--poll-timeout-seconds'); await (o.startReviewLoopFn || startReviewLoop)(context.slug, { implementer: flagValue(context.args, '--implementer') || undefined, reviewer: flagValue(context.args, '--reviewer') || undefined, focus: flagValue(context.args, '--focus') || 'all', maxAttempts, dryRun: context.args.includes('--dry-run'), reset: context.args.includes('--reset'), isContinue, verbose: context.args.includes('--verbose'), pollTimeoutSeconds: poll ? parseInt(poll, 10) : null, missionPath: flagValue(context.args, '--mission') || undefined, recordStageStatsSafeFn: o.recordStageStatsSafeFn || recordStageStatsSafe }); }
  async comment(context: ReviewWorkflowContext): Promise<void> { const o = context.options as typeof this._defaults; const message = readTextFlag(context.args, '--comment', '--comment-file', 'comment', o); if (!message) { (o.error || fmt.log.plainError)(fmt.status('FAIL', '--comment requires text via --comment "<text>" or --comment-file <path>.')); (o.exit || process.exit)(1); return; } await (o.commentRoundFn || commentRound)(context.slug, message, o); }
  async readComments(context: ReviewWorkflowContext): Promise<void> { const o = context.options as typeof this._defaults; await (o.readCommentsFn || readComments)(context.slug, o); }
  async submitReview(context: ReviewWorkflowContext): Promise<void> { const o = context.options as typeof this._defaults; const outcome = flagValue(context.args, '--submit-review'); if (!outcome) { (o.error || fmt.log.plainError)(fmt.status('FAIL', '--submit-review requires an outcome: px review <slug> --submit-review <approve|request-changes|comment> [--message "<summary>"|--message-file <path>]')); (o.exit || process.exit)(1); return; } await (o.submitReviewRoundFn || submitReviewRound)(context.slug, outcome, readTextFlag(context.args, '--message', '--message-file', 'review message', o) || '', o); }
  async consumeArtifacts(context: ReviewWorkflowContext): Promise<void> { const o = context.options as typeof this._defaults; await (o.consumeArtifactsFn || consumeArtifacts)(context.slug, o); }
  async close(context: ReviewWorkflowContext): Promise<void> { const o = context.options as typeof this._defaults; await (o.closeMissionPrFn || closeMissionPr)(context.slug, o); }
  async createEvent(context: ReviewWorkflowContext): Promise<void> { createEventHandler(context.slug, context.args, context.options); }
  async importLegacy(context: ReviewWorkflowContext): Promise<void> { importLegacyHandler(context.slug, context.args, context.options); }
  async backfillReview(context: ReviewWorkflowContext): Promise<void> { await backfillReviewHandler(context.slug, context.args, context.options); }
  async reconcileReview(context: ReviewWorkflowContext): Promise<void> { await reconcileInterruptedHandoffHandler(context.slug, context.args, context.options); }
  async status(context: ReviewWorkflowContext): Promise<void> { const o = context.options as typeof this._defaults; if (context.args.includes('--status')) { await showReviewStatus(context.slug, { ...o, readReviewStateFn: o.readReviewStateFn || readReviewState }); return; } const log = o.log || fmt.log.plain; const worktree = o.resolveWorktreeFn || resolveWorktree; const pr = (o.getPrStatusFn || getPrStatus)(missionBranchName(context.slug, process.cwd()), process.cwd()); log(fmt.status('INFO', `Review status for mission: ${fmt.slug(context.slug)}`)); if ((pr as Record<string, unknown>).exists) {log((pr as Record<string, unknown>).raw as string);} else { log(fmt.status('INFO', 'No active PR found for this mission.')); await this.staticReview(context, worktree); } const persisted = await Promise.resolve((o.readReviewStateFn || readReviewState)(context.slug)); if (persisted) {log(fmt.status('INFO', `Persisted reviewer state: reviewer=${fmt.agent(persisted.reviewer ?? '')} implementer=${fmt.agent(persisted.implementer ?? '')} round=${persisted.round}`));} }
  private async staticReview(context: ReviewWorkflowContext, worktreeFn: typeof resolveWorktree): Promise<void> { const o = context.options as typeof this._defaults; const log = o.log || fmt.log.plain; const error = o.error || fmt.log.plainError; const worktree = worktreeFn(context.slug) || process.cwd(); const result = (o.performStaticReviewFn || performStaticReview)(context.slug, { log, findMissionDir, findCheckpoints, readFileSync: fs.readFileSync, run: o.run || run, resolveWorktree: worktreeFn, rootDir: worktree, missionPath: flagValue(context.args, '--mission') || undefined }); if (result.findings?.length) { const resolution = (o.resolveTaskFileFn || resolveTaskFile)(context.slug, worktree); const implementer = resolution?.taskFile ? (o.getTaskImplementerFn || getTaskImplementer)(resolution.taskFile) : null; if (!implementer) {log(fmt.status('WARN', `Static review found ${result.findings.length} finding(s) but the implementer could not be resolved for ${fmt.slug(context.slug)} — not re-launching the implementer and not starting the review loop.`));} else { log(`\nStatic review found ${result.findings.length} finding(s). Re-launching implementer (${fmt.agent(implementer)}) with a targeted fix prompt...`); await (o.startAgentFn || startAgent)('active', { prompt: `Static review of your mission branch found the following issue(s). Fix them and commit, then stop:\n${result.findings.map((f: string) => `- ${f}`).join('\n')}`, worktree, agent: implementer, slug: context.slug }); } } else if (result.ok) { log(fmt.status('INFO', 'Static review passed — no findings. Mission branch is clean.')); const pr = (o.getPrStatusFn || getPrStatus)(missionBranchName(context.slug, process.cwd()), process.cwd()); if (!(pr as Record<string, unknown>).exists || (pr as Record<string, unknown>).state !== 'open') { log(fmt.status('INFO', 'No open PR found — submitting for review before finalizing static review...')); await (o.submitForReviewFn || submitForReview)(context.slug, true, o); } await (o.postStaticReviewCommentFn || postStaticReviewComment)(context.slug, formatStaticReviewSuccess(context.slug), { ...o, rootDir: worktree, log, error }); } }
}

export function createReviewWorkflowAdapter(options: ConstructorParameters<typeof ReviewWorkflowAdapter>[0] = {}) { return new ReviewWorkflowAdapter(options); }
