import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';
import _cp from 'child_process';
import * as fmt from '../../application/presentation/cli-format.js';
import { loadWorkflowConfig, resolveReviewAdapter } from '../config/product-config.js';
import { resolveForgejoSettings, reviewRemoteUrl } from '../forgejo/forgejo.js';
import ensureWorkflowGitignore from '../filesystem/gitignore.js';
import { PASSWORD_PROMPT_OPTIONS, apiRequest, buildTokenName, createToken, createTokenWithRetries, normalizeBaseUrl, parseRepoSlug, passwordPrompt, resolveBootstrapForgejoHome, tokenCreateViaOwnerToken, tokenFilePath, unique, writeToken } from './setup-review-auth.js';
import { ensureForgejoUser, ensureRepo, ensureRepoCollaborators, ensureReviewRemote, readConfiguredReviewRemote, suggestedForgejoUsers } from './setup-review-repository.js';
import { buildWorkflowConfig, evaluateReviewSetup, standardLayoutDescription, writeWorkflowConfig } from './setup-review-config.js';

const { spawnSync } = _cp;

export function parseYesNo(value: string | undefined, defaultValue?: boolean): boolean { if (typeof value !== 'string' || value.trim() === '') {return defaultValue ?? true;} return ['y', 'yes'].includes(value.trim().toLowerCase()) ? true : ['n', 'no'].includes(value.trim().toLowerCase()) ? false : defaultValue ?? true; }
export function defaultProductName(rootDir?: string): string { return path.basename(rootDir || process.cwd()) || 'Workflow Project'; }
export function defaultRepoSlug(rootDir?: string, ownerLogin?: string): string { return `${ownerLogin || 'human'}/${path.basename(rootDir || process.cwd()) || 'project'}`; }
export function detectPrimaryBranchDefault(rootDir?: string, options: { spawnSyncFn?: Function; configuredPrimaryBranch?: string | null } = {}): string {
  const spawnSyncFn = options.spawnSyncFn || spawnSync; const configuredPrimaryBranch = options.configuredPrimaryBranch || null;
  const listed = spawnSyncFn('git', ['-C', rootDir, 'branch', '--list', '--format=%(refname:short)', 'main', 'master'], { encoding: 'utf8' });
  const branches = listed.status === 0 ? (listed.stdout || '').split('\n').map((value: string) => value.trim()).filter(Boolean) : [];
  if (configuredPrimaryBranch && branches.includes(configuredPrimaryBranch)) {return configuredPrimaryBranch;}
  const current = spawnSyncFn('git', ['-C', rootDir, 'branch', '--show-current'], { encoding: 'utf8' }); const branch = current.status === 0 ? (current.stdout || '').trim() : '';
  return branch === 'main' || branch === 'master' ? branch : branches.includes('main') ? 'main' : branches.includes('master') ? 'master' : configuredPrimaryBranch || 'main';
}

export async function promptLine(prompt: string, options: { hidden?: boolean; input?: NodeJS.ReadStream; output?: NodeJS.WriteStream; createInterface?: Function } = {}): Promise<string> {
  const { hidden = false, input = process.stdin, output = process.stdout } = options;
  return await new Promise(resolve => {
    const rl = (options.createInterface || readline.createInterface)({ input, output, terminal: true });
    if (!hidden) {rl.question(prompt, (answer: string) => { rl.close(); resolve(answer.trim()); }); return;}
    const originalWrite = output.write.bind(output); const rlAny = rl as any;
    const mask = (chunk: string | Buffer) => [...(typeof chunk === 'string' ? chunk : String(chunk))].map(character => character === '\b' || character === '\x7f' ? '\b \b' : character >= ' ' && character !== '\u001b' ? '*' : '').join('');
    // @ts-expect-error runtime readline masking hook
    output.write = (chunk: string | Buffer, encoding: BufferEncoding | undefined, cb: (() => void) | undefined) => { if (!rlAny.stdoutMuted) {return originalWrite(chunk, encoding, cb);} const masked = mask(chunk); if (masked) {return originalWrite(masked, encoding, cb);} if (cb) {cb();} return true; };
    rlAny.stdoutMuted = true; originalWrite(prompt); rl.question('', (answer: string) => { output.write = originalWrite; rl.close(); output.write('\n'); resolve(answer.trim()); });
  });
}

export async function collectSetupAnswers(rootDir?: string, options: any = {}) {
  const { promptFn = promptLine, log = fmt.log.info, users = suggestedForgejoUsers(), resolveForgejoSettingsFn = resolveForgejoSettings } = options; const review = resolveForgejoSettingsFn(rootDir);
  const ownerLogin = (await promptFn(`Forgejo login with repo-create access [${parseRepoSlug(review.repo || '')?.owner || 'human'}]: `)) || parseRepoSlug(review.repo || '')?.owner || 'human'; const defaultUsers = users.join(',');
  log(fmt.status('INFO', `Forgejo setup target: ${review.url || 'unset'} / ${review.repo || 'unset'}`)); log(fmt.status('INFO', 'Forgejo review bootstrap will ask for one repo-creating login password and then optional passwords for each listed agent user.')); log(fmt.status('INFO', 'Leave an agent password blank to skip writing a token for that user on this machine.'));
  const ownerPassword = await promptFn(passwordPrompt(ownerLogin), PASSWORD_PROMPT_OPTIONS); const userList = (await promptFn(`Agent Forgejo users [${defaultUsers}]: `)) || defaultUsers; const agentUsers = unique(userList.split(',').map((value: string) => value.trim()).filter(Boolean)); const agentPasswords = [];
  for (const user of agentUsers) {const password = await promptFn(passwordPrompt(user, { allowBlank: true }), PASSWORD_PROMPT_OPTIONS); if (password) {agentPasswords.push({ user, password });}}
  return { baseUrl: review.url, repo: review.repo, ownerLogin, ownerPassword, agentPasswords, agentUsers };
}

export async function collectWizardAnswers(rootDir?: string, options: any = {}) {
  const { promptFn = promptLine, log = fmt.log.info, users = suggestedForgejoUsers(), loadWorkflowConfigFn = loadWorkflowConfig, detectPrimaryBranchDefaultFn = detectPrimaryBranchDefault } = options;
  const existing = loadWorkflowConfigFn(rootDir); const config = existing.found ? existing.config : null; const adapters = config?.adapters || {}; const review = adapters.review || {}; const tasks = adapters.tasks || {}; const missions = adapters.missions || {}; const verification = adapters.verification || {}; const primaryBranch = detectPrimaryBranchDefaultFn(rootDir, { configuredPrimaryBranch: missions.primaryBranch || null });
  const productName = (await promptFn(`Product name [${config?.product?.name || defaultProductName(rootDir)}]: `)) || config?.product?.name || defaultProductName(rootDir); log(fmt.status('INFO', `Standard workflow layout: ${standardLayoutDescription()}`)); const useDefaults = parseYesNo(await promptFn('Use the standard markdown task workflow layout and defaults? [Y/n]: '), true);
  const ownerLogin = (await promptFn(`Forgejo login with repo-create access [${parseRepoSlug(review.repo || '')?.owner || 'human'}]: `)) || parseRepoSlug(review.repo || '')?.owner || 'human'; const reviewRepo = (await promptFn(`Forgejo review repo [${review.repo || defaultRepoSlug(rootDir, ownerLogin)}]: `)) || review.repo || defaultRepoSlug(rootDir, ownerLogin); const baseUrl = normalizeBaseUrl((await promptFn(`Forgejo base URL [${review.baseUrl || 'http://localhost:3300'}]: `)) || review.baseUrl || 'http://localhost:3300'); const reviewRemote = (await promptFn(`Git review remote name [${review.remote || 'review'}]: `)) || review.remote || 'review';
  const defaults = useDefaults ? { tasksProvider: 'backlog-md', tasksStorage: 'backlog', missionsBaseDir: 'docs/missions', branchPrefix: 'mission/', primaryBranch, worktreePattern: '../<repo>-<slug>', verificationCommand: 'npm test', verificationDefaultArea: 'docs' } : { tasksProvider: 'backlog-md', tasksStorage: (await promptFn(`Task storage path [${tasks.storage || 'backlog'}]: `)) || tasks.storage || 'backlog', missionsBaseDir: (await promptFn(`Mission base dir [${missions.baseDir || 'docs/missions'}]: `)) || missions.baseDir || 'docs/missions', branchPrefix: (await promptFn(`Mission branch prefix [${missions.branchPrefix || 'mission/'}]: `)) || missions.branchPrefix || 'mission/', primaryBranch: (await promptFn(`Primary branch [${primaryBranch}]: `)) || primaryBranch, worktreePattern: (await promptFn(`Worktree pattern [${missions.worktreePattern || '../<repo>-<slug>'}]: `)) || missions.worktreePattern || '../<repo>-<slug>', verificationCommand: (await promptFn(`Verification command [${verification.command || 'npm test'}]: `)) || verification.command || 'npm test', verificationDefaultArea: (await promptFn(`Default verification area [${verification.defaultArea || 'docs'}]: `)) || verification.defaultArea || 'docs' };
  const bootstrapReview = parseYesNo(await promptFn('Create/update the Forgejo repo, token files, and review remote now? This will ask for the repo-owner password and optional agent passwords. [Y/n]: '), true); let ownerPassword = ''; const agentPasswords = []; let agentUsers = users;
  if (bootstrapReview) {log(fmt.status('INFO', 'Forgejo bootstrap is enabled. Hidden password prompts are next: first for the repo-creating login, then once per listed agent user.')); ownerPassword = await promptFn(passwordPrompt(ownerLogin), PASSWORD_PROMPT_OPTIONS); const userList = (await promptFn(`Agent Forgejo users [${users.join(',')}]: `)) || users.join(','); agentUsers = unique(userList.split(',').map((value: string) => value.trim()).filter(Boolean)); for (const user of agentUsers) {const password = await promptFn(passwordPrompt(user, { allowBlank: true }), PASSWORD_PROMPT_OPTIONS); if (password) {agentPasswords.push({ user, password });}}}
  return { productName, ownerLogin, baseUrl, reviewRepo, reviewRemote, bootstrapReview, ownerPassword, agentPasswords, agentUsers, ...defaults };
}

export function buildNonInteractiveAnswers(rootDir: string, options: any = {}) {
  const log = options.log || fmt.log.plain; const env = process.env; const productName = env.WORKFLOW_SETUP_PRODUCT_NAME || defaultProductName(rootDir); const reviewProvider = env.WORKFLOW_SETUP_REVIEW_PROVIDER || 'none'; const answers: any = { productName, reviewProvider, tasksProvider: 'backlog-md', tasksStorage: 'backlog', missionsBaseDir: 'docs/missions', branchPrefix: 'mission/', primaryBranch: detectPrimaryBranchDefault(rootDir), worktreePattern: '../<repo>-<slug>', verificationCommand: 'npm test', verificationDefaultArea: 'docs', bootstrapReview: false };
  if (reviewProvider === 'forgejo') {const ownerLogin = env.WORKFLOW_SETUP_OWNER_LOGIN || 'human'; const baseUrl = normalizeBaseUrl(env.WORKFLOW_SETUP_FORGEJO_URL || 'http://localhost:3300'); const reviewRepo = env.WORKFLOW_SETUP_FORGEJO_REPO || defaultRepoSlug(rootDir, ownerLogin); const agentUsers = env.WORKFLOW_SETUP_AGENT_USERS ? env.WORKFLOW_SETUP_AGENT_USERS.split(',').map(user => user.trim()).filter(Boolean) : suggestedForgejoUsers(); const ownerPassword = env.WORKFLOW_SETUP_OWNER_PASSWORD || ''; Object.assign(answers, { ownerLogin, baseUrl, reviewRepo, reviewRemote: env.WORKFLOW_SETUP_REVIEW_REMOTE || 'review', bootstrapReview: Boolean(ownerPassword), ownerPassword, agentPasswords: env.WORKFLOW_SETUP_AGENT_PASSWORD ? agentUsers.map(user => ({ user, password: env.WORKFLOW_SETUP_AGENT_PASSWORD || '' })) : [], agentUsers }); log(fmt.status('INFO', `Non-interactive setup: product=${productName}, repo=${reviewRepo}, url=${baseUrl}`));} else {log(fmt.status('INFO', `Non-interactive setup: product=${productName}, review=none (no Forgejo)`));}
  return answers;
}

export async function bootstrapReviewSurface(rootDir: string, setup: any, options: any = {}) {
  const { log = fmt.log.info, promptFn, requestFn = apiRequest, maxPasswordAttempts = 3, interactive = true, reviewRemoteUrlFn = reviewRemoteUrl } = options; const forgejoHome = resolveBootstrapForgejoHome(rootDir, options.forgejoHome); const repoInfo = parseRepoSlug(setup.repo); const baseUrl = normalizeBaseUrl(setup.baseUrl); if (!baseUrl || !repoInfo) {return { ok: false, error: 'workflow.config.json must define adapters.review.baseUrl and adapters.review.repo before setup can run.' };}
  const collaborators = unique([...(setup.agentUsers || []), ...(setup.agentPasswords || []).map((agent: any) => agent.user)].filter(Boolean)); let ownerToken: string | null = null; const warnings: any[] = []; const createdTokens: any[] = [];
  if (interactive) {const owner = await createTokenWithRetries({ ...setup, baseUrl }, setup.ownerLogin, setup.ownerPassword, { allowBlank: false, log, promptFn, maxAttempts: maxPasswordAttempts, requestFn }); if (!owner.ok) {return owner;} ownerToken = (owner as any).token; createdTokens.push({ user: setup.ownerLogin, path: writeToken(setup.ownerLogin, ownerToken as string, forgejoHome) }); for (const agent of setup.agentPasswords) {if (agent.password) {const user = ensureForgejoUser(baseUrl, agent.user, setup.ownerLogin, setup.ownerPassword, agent.password, requestFn); if (!user.ok) {warnings.push({ user: agent.user, error: user.error, response: user.response }); continue;} if (user.created) {log(fmt.status('PASS', `Created Forgejo user ${agent.user}.`));}} const token = await createTokenWithRetries({ ...setup, baseUrl }, agent.user, agent.password, { allowBlank: true, log, promptFn, maxAttempts: maxPasswordAttempts, requestFn }); if (!token.ok) {warnings.push({ user: agent.user, error: (token as any).error, response: (token as any).response });} else if (!(token as any).skipped) {createdTokens.push({ user: agent.user, path: writeToken(agent.user, (token as any).token, forgejoHome) });}}} else {const file = path.join(forgejoHome, 'tokens', setup.ownerLogin); ownerToken = fs.existsSync(file) ? fs.readFileSync(file, 'utf8').trim() : null; if (!ownerToken) {return { ok: false, error: `No owner token found for ${setup.ownerLogin} at ${file}. A token file for an existing user (typically human) is required to bootstrap new agent tokens.` };}}
  const repo = ensureRepo(baseUrl, setup.repo, setup.ownerLogin, ownerToken as string, requestFn); if (!repo.ok) {return repo;} const collaboratorResult = ensureRepoCollaborators(baseUrl, setup.repo, ownerToken as string, collaborators, 'write', requestFn); if (!collaboratorResult.ok) {return collaboratorResult;}
  if (!interactive) {const tokens = tokenCreateViaOwnerToken(baseUrl, setup.repo, ownerToken as string, setup.agentPasswords, repoInfo, { requestFn, writeTokenFn: writeToken, forgejoHome }); if (!tokens.ok) {return tokens;} createdTokens.push(...tokens.createdTokens); warnings.push(...tokens.warnings);}
  const remoteUrl = reviewRemoteUrlFn(rootDir); const remoteName = resolveReviewAdapter(rootDir).remote || 'review'; const remote = remoteUrl ? ensureReviewRemote(rootDir, remoteName, remoteUrl) : { ok: true }; if (!remote.ok) {return remote;} if (collaboratorResult.created.length) {log(fmt.status('PASS', `Granted write access on ${setup.repo} to ${collaboratorResult.created.join(', ')}`));} log(fmt.status('PASS', `Forgejo repo ${setup.repo} ${repo.created ? 'created' : 'already exists'}.`)); for (const token of createdTokens) {log(fmt.status('PASS', `Wrote Forgejo token for ${token.user} to ${token.path}`));} for (const warning of warnings) {log(fmt.status('WARN', `Skipping Forgejo token for ${warning.user}: ${warning.error}`)); if (warning.response) {log(fmt.status('INFO', `Forgejo response for ${warning.user}: ${JSON.stringify(warning.response)}`));}} log(fmt.status('PASS', `Review remote "${remoteName}" now points at ${remoteUrl}`)); return interactive ? { ok: true, warnings } : { ok: true, warnings, createdTokens };
}

export async function setupReview(_args: any[], options: any = {}) { const rootDir = options.rootDir || process.cwd(); const log = options.log || fmt.log.plain; const error = options.error || fmt.log.plainError; const exit = options.exit || process.exit; const result = await bootstrapReviewSurface(rootDir, await collectSetupAnswers(rootDir, { promptFn: options.promptFn || promptLine, log }), { ...options, forgejoHome: resolveBootstrapForgejoHome(rootDir, options.forgejoHome) }); if (!result.ok) {error(fmt.status('FAIL', (result as any).error || '')); if ((result as any).response) {error(fmt.status('INFO', `Forgejo response: ${JSON.stringify((result as any).response)}`));} exit(1);} }
export async function runVerifyEnv(rootDir: string, options: { verifyFn?: Function } = {}) { return (options.verifyFn || ((cwd: string) => spawnSync('node', ['workflow', 'verify-env'], { cwd, stdio: 'inherit', encoding: 'utf8' })))(rootDir); }
export async function setupWizard(args: any[], options: any = {}) { const rootDir = options.rootDir || process.cwd(); const log = options.log || fmt.log.plain; const error = options.error || fmt.log.plainError; const exit = options.exit || process.exit; const answers: any = (args?.includes('--non-interactive') || process.env.WORKFLOW_SETUP_NON_INTERACTIVE === '1') ? buildNonInteractiveAnswers(rootDir, { log }) : await collectWizardAnswers(rootDir, { ...options, promptFn: options.promptFn || promptLine, log }); log(fmt.status('PASS', `Wrote ${writeWorkflowConfig(rootDir, buildWorkflowConfig(answers))}`)); const gitignore = ensureWorkflowGitignore(rootDir, { logFn: log }); if (gitignore.created) {log(fmt.status('PASS', `Created .gitignore with ${gitignore.appended} workflow entries in ${fmt.path(rootDir)}`));} else if (gitignore.appended > 0) {log(fmt.status('PASS', `Appended ${gitignore.appended} workflow entries to .gitignore in ${fmt.path(rootDir)}`));} else if (gitignore.skipped) {log(fmt.status('INFO', `.gitignore in ${fmt.path(rootDir)}: ${gitignore.reason === 'symlink' ? 'symbolic link (skipped)' : 'not a git repo (skipped)'}`));} else {log(fmt.status('PASS', `.gitignore in ${fmt.path(rootDir)} already contains all workflow entries`));} if (answers.bootstrapReview) {const result = await bootstrapReviewSurface(rootDir, { baseUrl: answers.baseUrl, repo: answers.reviewRepo, ownerLogin: answers.ownerLogin, ownerPassword: answers.ownerPassword, agentPasswords: answers.agentPasswords, agentUsers: answers.agentUsers }, { ...options, forgejoHome: resolveBootstrapForgejoHome(rootDir, options.forgejoHome) }); if (!result.ok) {error(fmt.status('FAIL', (result as any).error || '')); exit(1); return;}} else {log(fmt.status('INFO', 'Skipped Forgejo bootstrap. You can run `px setup-review` later if needed.'));} const verified = await runVerifyEnv(rootDir, options); if (verified?.status) {exit(verified.status);} }

export { apiRequest, buildTokenName, buildWorkflowConfig, createToken, ensureForgejoUser, ensureRepo, ensureReviewRemote, evaluateReviewSetup, parseRepoSlug, readConfiguredReviewRemote, resolveBootstrapForgejoHome, standardLayoutDescription, tokenFilePath, writeToken, writeWorkflowConfig };
