/**
 * Reproduction test for task-1390: px shell-init bash broken after
 * TypeScript conversion.
 *
 * The distribution build compiles px.ts → dist/px.js. TypeScript historically
 * strips shebang lines from compiled output, leaving the CLI without a
 * #!/usr/bin/env node header. Without the shebang, px.js cannot be
 * executed directly and the npm bin wrapper may behave unexpectedly in
 * certain environments, breaking the shell function generated by
 * `px shell-init bash` (which uses `command px "$@"` to invoke the
 * globally installed px binary).
 *
 * This test verifies that the compiled px.js is directly executable
 * (has the shebang) and that `node dist/px.js shell-init bash` produces
 * valid shell output.
 *
 * Red at parent commit (before fix): px.js missing shebang or
 *   shell-init bash fails to produce valid output.
 * Green after fix: px.js has shebang and shell-init bash works.
 */
const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const PX_JS = path.resolve(__dirname, '..', 'dist', 'px.js');

test('dist/px.js has shebang for direct execution (task-1390)', () => {
  assert.ok(fs.existsSync(PX_JS), 'dist/px.js must exist after npm run build');
  const content = fs.readFileSync(PX_JS, 'utf8');
  const firstLine = content.split('\n')[0];
  assert.equal(
    firstLine,
    '#!/usr/bin/env node',
    'px.js must start with #!/usr/bin/env node shebang for direct execution',
  );
});

test('dist/px.js shell-init bash produces valid shell function (task-1390)', () => {
  const result = spawnSync('node', [PX_JS, 'shell-init', 'bash'], {
    encoding: 'utf8',
    timeout: 10000,
  });
  assert.equal(result.status, 0, `shell-init bash exited ${result.status}: ${result.stderr}`);
  const output = result.stdout;
  assert.ok(
    output.includes('px() {'),
    'output must contain the px shell function definition',
  );
  assert.ok(
    output.includes('command px'),
    'output must reference command px for PATH resolution',
  );
  assert.ok(
    output.includes('PIPESTATUS'),
    'output must capture bash pipe status for exit code propagation',
  );
});
