
/**
 * Reproduction test for task-1390: px shell-init bash broken after
 * TypeScript conversion.
 *
 * The distribution build emits the CLI as a bundle. TypeScript and bundlers
 * historically strip shebang lines from generated output, leaving the CLI
 * without a #!/usr/bin/env node header. Without the shebang the entry cannot be
 * executed directly and the npm bin wrapper may behave unexpectedly in certain
 * environments, breaking the shell function generated by `px shell-init bash`
 * (which uses `command px "$@"` to invoke the globally installed px binary).
 *
 * This test verifies that the shipped entry point is directly executable (has
 * the shebang) and that running `shell-init bash` from it produces valid shell
 * output. TASK-2288 retired the transitional dist/px.js, so the assertion now
 * covers build/px.mjs — the target of package.json's `bin.px`.
 *
 * Red at parent commit (before fix): the entry is missing its shebang, or
 *   shell-init bash fails to produce valid output.
 * Green after fix: the entry has a shebang and shell-init bash works.
 */
const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const PX_ENTRY = path.resolve(__dirname, '..', 'build', 'px.mjs');

test('build/px.mjs has shebang for direct execution (task-1390)', () => {
  assert.ok(fs.existsSync(PX_ENTRY), 'build/px.mjs must exist after npm run build');
  const content = fs.readFileSync(PX_ENTRY, 'utf8');
  const firstLine = content.split('\n')[0];
  assert.equal(
    firstLine,
    '#!/usr/bin/env node',
    'build/px.mjs must start with #!/usr/bin/env node shebang for direct execution',
  );
});

test('build/px.mjs shell-init bash produces valid shell function (task-1390)', () => {
  const result = spawnSync('node', [PX_ENTRY, 'shell-init', 'bash'], {
    encoding: 'utf8',
    timeout: 10000,
  });
  assert.equal(result.status, 0, `shell-init bash exited ${result.status}: ${result.stderr}`);
  const output = result.stdout;
  assert.ok(
    output.includes('px() {'),
    'output must contain the px shell function definition',
  );
  assert.ok(
    output.includes('command px'),
    'output must reference command px for PATH resolution',
  );
  assert.ok(
    output.includes('PIPESTATUS'),
    'output must capture bash pipe status for exit code propagation',
  );
});
