import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';

const ignorePattern = '^_';
const argsIgnorePattern = '^_|^name$';
const caughtErrorsIgnorePattern = '^_';
const varsIgnorePattern = '^_';

export default [
  {
    ignores: [
      // Compiled output from TS migration (generated by `npm run build:cjs`)
      'lib/core/*.js',
      'lib/agents/*.js',
      'lib/tools/*.js',
      'lib/review/*.js',
      'lib/commands/*.js',
      'lib/*.js',
      'dist/',
      'node_modules/',
      'graphify-out/',
      '.forgejo-local/',
    ],
  },
  {
    files: ['**/*.ts'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 2024,
        sourceType: 'module',
      },
      globals: {
        console: 'readonly',
        process: 'readonly',
        __filename: 'readonly',
        __dirname: 'readonly',
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        Buffer: 'readonly',
        BufferEncoding: 'readonly',
        NodeJS: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        URL: 'readonly',
        Headers: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        fetch: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['warn', { argsIgnorePattern, varsIgnorePattern, caughtErrorsIgnorePattern }],
      'valid-typeof': 'error',
      'no-unreachable': 'error',
      'no-async-promise-executor': 'error',
      'eqeqeq': 'error',
      'curly': 'error',
      'no-var': 'error',
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  {
    files: ['**/*.js'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 2024,
        sourceType: 'module',
      },
      globals: {
        console: 'readonly',
        process: 'readonly',
        __filename: 'readonly',
        __dirname: 'readonly',
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        Buffer: 'readonly',
        BufferEncoding: 'readonly',
        NodeJS: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        URL: 'readonly',
        Headers: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        fetch: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['warn', { argsIgnorePattern, varsIgnorePattern, caughtErrorsIgnorePattern }],
      'valid-typeof': 'error',
      'no-unreachable': 'error',
      'no-async-promise-executor': 'error',
      'eqeqeq': 'error',
      'curly': 'error',
      'no-var': 'error',
    },
  },
];
