sonar.projectKey=parallix
sonar.projectName=Parallix
sonar.host.url=http://127.0.0.1:9000
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=**/node_modules/**,**/build/**,**/coverage/**,**/graphify-out/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
