project_name: "parallix"
default_status: "backlog"
statuses: ["backlog", "refined", "active", "review", "ready-for-integration", "done"]
labels: []
definition_of_done: []
date_format: yyyy-mm-dd
max_column_width: 20
default_editor: "code --wait"
auto_open_browser: true
default_port: 6480
remote_operations: false
auto_commit: true
zero_padded_ids: 3
bypass_git_hooks: false
check_active_branches: true
active_branch_days: 30
task_prefix: "task"
